apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: python-demo-app
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: python-demo-app
  targetCPUUtilizationPercentage: 5

